"use node";

import { v } from "convex/values";
import { action, internalAction } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { GetObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { getS3Client, BUCKET_NAME } from "./s3";
import { isFeatureEnabled } from "./featureFlags";

/**
 * Self-contained signed package: the frozen contract body + each signer's
 * signature block + a Certificate of Completion (hash, parties, full audit
 * trail). Written to R2 as one HTML file anyone can open and print to PDF; the
 * content hash lets a court independently verify the body was never altered.
 * A true server-rendered PDF is a follow-up (no PDF renderer in the runtime).
 */

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function fmt(ts: number | null): string {
  if (!ts) return "—";
  return new Date(ts).toISOString().replace("T", " ").replace(/\.\d+Z$/, " UTC");
}

function buildSignedPackageHtml(d: {
  title: string;
  contentHash: string | null;
  completedAt: number | null;
  frozenContentHtml: string;
  signers: Array<{
    name: string;
    email: string;
    role: string;
    status: string;
    signedAt: number | null;
    consentedAt: number | null;
    ip: string | null;
    userAgent: string | null;
    typedSignatureName: string | null;
    signatureDataUrl: string | null;
  }>;
  audit: Array<{
    action: string;
    actorName: string | null;
    ip: string | null;
    at: number;
    metadata: string | null;
  }>;
}): string {
  const signerBlocks = d.signers
    .map((s) => {
      const sig = s.signatureDataUrl
        ? `<img src="${esc(s.signatureDataUrl)}" alt="signature" style="max-height:64px;max-width:280px;border-bottom:2px solid #1a1a1a;" />`
        : `<div style="font-family:'Segoe Script',cursive;font-size:28px;border-bottom:2px solid #1a1a1a;display:inline-block;padding:0 8px 4px;">${esc(s.typedSignatureName ?? s.name)}</div>`;
      return `
      <div style="border:2px solid #1a1a1a;padding:16px;margin:12px 0;">
        ${sig}
        <div style="margin-top:8px;font-size:13px;">
          <strong>${esc(s.name)}</strong> &lt;${esc(s.email)}&gt; · ${esc(s.role)}<br/>
          Status: <strong>${esc(s.status)}</strong> · Signed: ${fmt(s.signedAt)}<br/>
          Consented (E-SIGN): ${fmt(s.consentedAt)}<br/>
          IP: <code>${esc(s.ip ?? "—")}</code><br/>
          <span style="color:#888;font-size:11px;">UA: ${esc(s.userAgent ?? "—")}</span>
        </div>
      </div>`;
    })
    .join("");

  const auditRows = d.audit
    .map(
      (e) => `
      <tr>
        <td style="padding:4px 8px;border:1px solid #ccc;font-family:monospace;">${fmt(e.at)}</td>
        <td style="padding:4px 8px;border:1px solid #ccc;">${esc(e.action)}</td>
        <td style="padding:4px 8px;border:1px solid #ccc;">${esc(e.actorName ?? "—")}</td>
        <td style="padding:4px 8px;border:1px solid #ccc;font-family:monospace;">${esc(e.ip ?? "—")}</td>
      </tr>`,
    )
    .join("");

  return `<!doctype html>
<html><head><meta charset="utf-8" />
<title>${esc(d.title)} — Signed</title>
<style>body{font-family:ui-sans-serif,system-ui,sans-serif;color:#1a1a1a;max-width:820px;margin:0 auto;padding:40px 24px;background:#f0f0e8;}h1{font-weight:900;}h2{border-bottom:2px solid #1a1a1a;padding-bottom:4px;margin-top:40px;}table{border-collapse:collapse;width:100%;font-size:12px;}code{font-size:12px;}</style>
</head><body>
<h1>${esc(d.title)}</h1>
<p style="font-family:monospace;font-size:12px;color:#444;">
  Completed: ${fmt(d.completedAt)}<br/>
  Document SHA-256: <code>${esc(d.contentHash ?? "—")}</code>
</p>

<h2>Agreement</h2>
<div>${d.frozenContentHtml}</div>

<h2>Signatures</h2>
${signerBlocks || "<p>No signatures.</p>"}

<h2>Certificate of Completion — Audit Trail</h2>
<table>
  <thead><tr>
    <th style="padding:4px 8px;border:1px solid #ccc;text-align:left;">Time (UTC)</th>
    <th style="padding:4px 8px;border:1px solid #ccc;text-align:left;">Event</th>
    <th style="padding:4px 8px;border:1px solid #ccc;text-align:left;">Actor</th>
    <th style="padding:4px 8px;border:1px solid #ccc;text-align:left;">IP</th>
  </tr></thead>
  <tbody>${auditRows}</tbody>
</table>
<p style="color:#888;font-size:11px;margin-top:24px;">
  This record was generated by snip. Integrity can be verified by re-computing the
  SHA-256 of the agreement body above and comparing it to the hash shown.
</p>
</body></html>`;
}

export const finalizeSignedPackage = internalAction({
  args: { contractId: v.id("contracts") },
  returns: v.object({ ok: v.boolean(), key: v.optional(v.string()) }),
  handler: async (
    ctx,
    args,
  ): Promise<{ ok: boolean; key?: string }> => {
    if (!isFeatureEnabled("objectStorage")) return { ok: false };
    const data = await ctx.runQuery(
      internal.contractsTable.getSignedPackageData,
      { contractId: args.contractId },
    );
    if (!data) return { ok: false };
    const html = buildSignedPackageHtml(data);
    const key = `contracts/${args.contractId}/signed-package.html`;
    const s3 = getS3Client();
    await s3.send(
      new PutObjectCommand({
        Bucket: BUCKET_NAME,
        Key: key,
        Body: html,
        ContentType: "text/html; charset=utf-8",
      }),
    );
    await ctx.runMutation(internal.contractsTable.setSignedPackageKey, {
      contractId: args.contractId,
      key,
    });
    return { ok: true, key };
  },
});

// Member-gated download link for the signed package.
export const getSignedPackageUrl = action({
  args: { contractId: v.id("contracts") },
  returns: v.union(v.string(), v.null()),
  handler: async (ctx, args): Promise<string | null> => {
    const key = await ctx.runQuery(api.contractsTable.getSignedPackageKey, {
      contractId: args.contractId,
    });
    if (!key) return null;
    const s3 = getS3Client();
    const command = new GetObjectCommand({ Bucket: BUCKET_NAME, Key: key });
    return await getSignedUrl(s3, command, { expiresIn: 600 });
  },
});
