import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  teams: defineTable({
    name: v.string(),
    slug: v.string(),
    ownerClerkId: v.string(),
    plan: v.union(
      v.literal("basic"),
      v.literal("pro"),
      v.literal("free"),
      v.literal("team")
    ),
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    stripePriceId: v.optional(v.string()),
    billingStatus: v.optional(v.string()),
    // Stripe Connect — separate from the SaaS subscription above. This is how
    // the team receives payments from their own clients via paywalled share links.
    stripeConnectAccountId: v.optional(v.string()),
    stripeConnectStatus: v.optional(
      v.union(
        v.literal("pending"),
        v.literal("active"),
        v.literal("restricted"),
        v.literal("disabled")
      )
    ),
    stripeConnectChargesEnabled: v.optional(v.boolean()),
    stripeConnectPayoutsEnabled: v.optional(v.boolean()),
    // Shared secret used by the DaVinci Resolve / Premiere plugin to
    // authenticate against /timelines/snapshot. Rotatable. The plugin
    // sends it as `Authorization: Bearer <token>`. Owner-only mutation
    // generates this; we look up the team by indexing on this token.
    pluginToken: v.optional(v.string()),
  })
    .index("by_slug", ["slug"])
    .index("by_owner", ["ownerClerkId"])
    .index("by_stripe_customer_id", ["stripeCustomerId"])
    .index("by_stripe_subscription_id", ["stripeSubscriptionId"])
    .index("by_stripe_connect_account", ["stripeConnectAccountId"])
    .index("by_plugin_token", ["pluginToken"]),

  teamMembers: defineTable({
    teamId: v.id("teams"),
    userClerkId: v.string(),
    userEmail: v.string(),
    userName: v.string(),
    userAvatarUrl: v.optional(v.string()),
    role: v.union(
      v.literal("owner"),
      v.literal("admin"),
      v.literal("member"),
      v.literal("viewer")
    ),
  })
    .index("by_team", ["teamId"])
    .index("by_user", ["userClerkId"])
    .index("by_team_and_user", ["teamId", "userClerkId"])
    .index("by_team_and_email", ["teamId", "userEmail"]),

  teamInvites: defineTable({
    teamId: v.id("teams"),
    email: v.string(),
    role: v.union(
      v.literal("admin"),
      v.literal("member"),
      v.literal("viewer")
    ),
    invitedByClerkId: v.string(),
    invitedByName: v.string(),
    token: v.string(),
    expiresAt: v.number(),
  })
    .index("by_team", ["teamId"])
    .index("by_email", ["email"])
    .index("by_token", ["token"]),

  projects: defineTable({
    teamId: v.id("teams"),
    name: v.string(),
    description: v.optional(v.string()),
    // Contract — agency↔client agreement.
    //
    // The canonical editable form lives in `contentHtml` (Tiptap output).
    // On save / explicit download, we generate a .docx file from that HTML
    // client-side via html-to-docx. Agencies can also upload an existing
    // .docx (mammoth converts to HTML for editing).
    //
    // `docxS3Key` is set when the deployment has object storage configured
    // and we've persisted the latest .docx to S3 so it can be linked into
    // e-sign flows (Dropbox Sign / Docusign) later. Without storage this
    // stays null and the agency downloads ad-hoc.
    //
    // Signing is demo-only for v1 (sets signedAt); production wiring goes
    // through an external e-sign action.
    contract: v.optional(
      v.object({
        contentHtml: v.string(),
        scope: v.optional(v.string()),
        deliverablesSummary: v.optional(v.string()),
        priceCents: v.optional(v.number()),
        currency: v.optional(v.string()),
        revisionsAllowed: v.optional(v.number()),
        deadline: v.optional(v.string()),
        clientName: v.optional(v.string()),
        clientEmail: v.optional(v.string()),
        docxS3Key: v.optional(v.string()),
        originalFilename: v.optional(v.string()),
        lastSavedAt: v.optional(v.number()),
        sentForSignatureAt: v.optional(v.number()),
        signedAt: v.optional(v.number()),
        signedByName: v.optional(v.string()),
        // Structured contract — generated by the wizard. When `clauses`
        // is set, the contract editor renders the tabbed clause view.
        // When absent (legacy contracts), the old single-canvas editor
        // still works against `contentHtml`. New flow always populates
        // both: clauses[] is the source of truth, contentHtml is the
        // serialized form for .docx export.
        projectType: v.optional(
          v.union(
            v.literal("logo_design"),
            v.literal("video_production"),
            v.literal("web_design"),
            v.literal("photography"),
            v.literal("brand_identity"),
            v.literal("copywriting"),
            v.literal("music"),
            v.literal("animation"),
            v.literal("custom"),
          ),
        ),
        wizardAnswers: v.optional(v.string()), // JSON blob, schema lives in src/lib/contractTemplates.ts
        clauses: v.optional(
          v.array(
            v.object({
              id: v.string(),
              sectionKey: v.string(),
              title: v.string(),
              bodyHtml: v.string(),
              state: v.union(
                v.literal("draft"),
                v.literal("pending"),
                v.literal("accepted"),
                v.literal("disputed"),
              ),
              required: v.boolean(),
              order: v.number(),
              sourceAnswerId: v.optional(v.string()),
              proposedBody: v.optional(v.string()),
              comments: v.optional(
                v.array(
                  v.object({
                    author: v.string(),
                    text: v.string(),
                    createdAt: v.number(),
                  }),
                ),
              ),
            }),
          ),
        ),
      }),
    ),
    /**
     * Soft-delete marker. When set, the project is hidden from team
     * listings and counts as trashed; it stays in the table until
     * either explicitly purged or auto-expired (we'll add a scheduled
     * sweep later). Restore clears this back to undefined.
     */
    deletedAt: v.optional(v.number()),
    deletedByName: v.optional(v.string()),
  })
    .index("by_team", ["teamId"])
    .index("by_team_and_deleted", ["teamId", "deletedAt"]),

  // Subfolders inside a project — Google-Drive-style nesting. Optional
  // parentFolderId allows arbitrary depth; null/missing means the folder
  // sits at the project root. Both the folder itself and its contents are
  // scoped to a single project — there's no cross-project move.
  folders: defineTable({
    projectId: v.id("projects"),
    parentFolderId: v.optional(v.id("folders")),
    name: v.string(),
    createdByClerkId: v.string(),
    createdByName: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_parent", ["projectId", "parentFolderId"]),

  videos: defineTable({
    projectId: v.id("projects"),
    // Optional folder inside the project. null/missing = root.
    folderId: v.optional(v.id("folders")),
    uploadedByClerkId: v.string(),
    uploaderName: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    visibility: v.union(v.literal("public"), v.literal("private")),
    publicId: v.string(),
    // Mux video references — the "full" asset.
    // muxPlaybackId is the public playback ID used for in-team review.
    // muxSignedPlaybackId is a signed-policy playback ID on the SAME asset,
    // used post-payment on paywalled share links (so we can issue short-TTL JWTs).
    muxUploadId: v.optional(v.string()),
    muxAssetId: v.optional(v.string()),
    muxPlaybackId: v.optional(v.string()),
    muxSignedPlaybackId: v.optional(v.string()),
    muxAssetStatus: v.optional(
      v.union(
        v.literal("preparing"),
        v.literal("ready"),
        v.literal("errored")
      )
    ),
    // Mux auto-generated captions track. Populated by muxActions when
    // `video.asset.track.ready` fires for a text track. The captions VTT
    // URL is `https://stream.mux.com/{muxPlaybackId}/text/{muxCaptionsTrackId}.vtt`.
    muxCaptionsTrackId: v.optional(v.string()),
    // Mux "preview" asset — a separate ingest with a per-team watermark overlay
    // and resolution capped at 360p. Shown pre-payment on paywalled share links.
    // Mux overlays are applied at ingest time, hence the second asset.
    muxPreviewAssetId: v.optional(v.string()),
    muxPreviewPlaybackId: v.optional(v.string()),
    muxPreviewAssetStatus: v.optional(
      v.union(
        v.literal("preparing"),
        v.literal("ready"),
        v.literal("errored")
      )
    ),
    // Persisted reason when muxPreviewAssetStatus flips to "errored", and
    // the wall-clock time of the most recent write to the preview-asset
    // fields. Used by the share page to surface why the preview died and
    // by the playback action to stall-detect a stuck "preparing" asset.
    muxPreviewAssetError: v.optional(v.string()),
    muxPreviewAssetUpdatedAt: v.optional(v.number()),
    // Mux static renditions = downloadable MP4 "proxies" (modern replacement
    // for mp4_support, which is "none" on our assets). Doubles as the edit
    // proxy the LucidLink-style drive serves. Requested on-demand (each is a
    // re-encode → costs money) via videoActions.requestProxies; populated by
    // the `video.asset.static_rendition.ready|.errored` webhooks. Mirrors the
    // muxPreviewAsset* pattern: one array entry per resolution. `name` is the
    // Mux file name used in the URL (e.g. "720p.mp4"). See plans/proxies-unified.md.
    staticRenditions: v.optional(
      v.array(
        v.object({
          name: v.string(), // e.g. "720p.mp4" | "highest.mp4" | "audio.m4a"
          resolution: v.string(), // e.g. "720p" | "1080p" | "highest" | "audio-only"
          status: v.union(
            v.literal("preparing"),
            v.literal("ready"),
            v.literal("errored"),
            v.literal("skipped"),
          ),
          ext: v.string(), // "mp4" | "m4a"
          filesizeBytes: v.optional(v.number()),
          error: v.optional(v.string()),
          // When the ready rendition has been mirrored into R2 for the
          // LucidLink-style drive, this is its object key under
          // projects/<teamSlug>/<projectId>/proxies/<videoId>/<name>. Absent =
          // download-only (served from Mux); present = also on the drive.
          r2Key: v.optional(v.string()),
        }),
      ),
    ),
    staticRenditionsUpdatedAt: v.optional(v.number()),
    watermarkOverlayKey: v.optional(v.string()),
    // Image-class items (jpg/png/webp/gif) skip Mux and get a sharp-rendered
    // watermarked low-res preview instead. Same gating semantics as the video
    // preview asset: served pre-payment, swapped for the original on paid
    // grants. Stored as an S3 key so we can issue signed URLs with short TTL.
    imagePreviewS3Key: v.optional(v.string()),
    imagePreviewStatus: v.optional(
      v.union(
        v.literal("pending"),
        v.literal("ready"),
        v.literal("errored"),
      ),
    ),
    // Canva-style per-video paywall. Optional. When set, the Download
    // button on the video itself (dashboard player, share page) becomes a
    // "Download — $X" checkout. shareLinks can still ALSO have their own
    // paywall and they compose with this one. Team members downloading
    // from their own dashboard always bypass — this affects external
    // viewers (anyone hitting via share grant) by default. The download
    // gate in videoActions checks both video-level and link-level paywall.
    paywall: v.optional(
      v.object({
        priceCents: v.number(),
        currency: v.string(),
        description: v.optional(v.string()),
      }),
    ),
    // Metadata
    s3Key: v.optional(v.string()),
    duration: v.optional(v.number()),
    thumbnailUrl: v.optional(v.string()),
    fileSize: v.optional(v.number()),
    contentType: v.optional(v.string()),
    uploadError: v.optional(v.string()),
    // Free-form tags (bulk-editable). Optional; absent = no tags.
    tags: v.optional(v.array(v.string())),
    status: v.union(
      v.literal("uploading"),
      v.literal("processing"),
      v.literal("ready"),
      v.literal("failed")
    ),
    workflowStatus: v.union(
      v.literal("review"),
      v.literal("rework"),
      v.literal("done"),
    ),
    // Frame.io-style upload stacks. Each upload is its own row, but rows
    // in the same conceptual "video" share a lineageId (the root row's
    // _id). versionNumber is the position in the stack starting at 1.
    // isCurrentVersion marks exactly one row per lineage as the one
    // surfaced in the project grid and as the default playable when you
    // open any video in the lineage. Optional on existing rows so we
    // don't need a migration — readers fall back to "single-version
    // lineage where the video is its own root".
    lineageId: v.optional(v.id("videos")),
    versionNumber: v.optional(v.number()),
    isCurrentVersion: v.optional(v.boolean()),
    versionLabel: v.optional(v.string()),
    // Asset classification. Missing/undefined behaves as "video" (the
    // legacy default) — most rows in production are videos so the field
    // is only persisted on new sequence/image/audio assets to avoid a
    // backfill. Currently:
    //   "image_sequence" → DPX/EXR/PNG sequence (sequenceFrameKeys set)
    //   "audio"          → mp3/wav/etc. (downloaded only, no player yet)
    // We don't tag "video" or "image" explicitly — those derive from
    // muxAssetId / imagePreviewS3Key / contentType as today.
    kind: v.optional(
      v.union(
        v.literal("video"),
        v.literal("image"),
        v.literal("audio"),
        v.literal("image_sequence"),
      ),
    ),
    // Image sequence fields. Populated when an upload batch contains 3+
    // files matching a `name.NNNN.ext` pattern. Frame keys are R2 keys
    // for the original frames in zero-padded index order. The optional
    // stitched MP4 / Mux asset uses the existing muxAssetId/muxPlaybackId
    // fields so the player can reuse the normal playback flow.
    sequenceFrameKeys: v.optional(v.array(v.string())),
    sequenceFps: v.optional(v.number()),
    sequenceStem: v.optional(v.string()),
    sequenceFrameExt: v.optional(v.string()),
    // Status of the optional ffmpeg → Mux stitching job. Pending/preparing
    // while we transcode; ready once muxPlaybackId is set; errored if the
    // ffmpeg binary isn't available on the runtime. The frame-grid UI
    // works regardless of this status.
    sequenceStitchStatus: v.optional(
      v.union(
        v.literal("pending"),
        v.literal("preparing"),
        v.literal("ready"),
        v.literal("errored"),
      ),
    ),
    sequenceStitchError: v.optional(v.string()),
    // Soft-delete marker. When set, the video disappears from project /
    // folder listings and shows up in the "Recently deleted" page where
    // it can be restored or purged. Mirrors the same pattern on projects.
    deletedAt: v.optional(v.number()),
    deletedByName: v.optional(v.string()),
  })
    .index("by_project", ["projectId"])
    .index("by_public_id", ["publicId"])
    .index("by_mux_upload_id", ["muxUploadId"])
    .index("by_mux_asset_id", ["muxAssetId"])
    .index("by_mux_playback_id", ["muxPlaybackId"])
    .index("by_mux_preview_asset_id", ["muxPreviewAssetId"])
    .index("by_lineage", ["lineageId"])
    .index("by_folder", ["folderId"]),

  comments: defineTable({
    videoId: v.id("videos"),
    userClerkId: v.string(),
    userName: v.string(),
    userAvatarUrl: v.optional(v.string()),
    text: v.string(),
    timestampSeconds: v.number(),
    parentId: v.optional(v.id("comments")),
    resolved: v.boolean(),
  })
    .index("by_video", ["videoId"])
    .index("by_video_and_timestamp", ["videoId", "timestampSeconds"])
    .index("by_parent", ["parentId"]),

  // Bundles let a single share link cover multiple items at once with one
  // paywall and one grant. Two kinds:
  //   • folder    — live: resolves to the current contents of folderId. New
  //                 uploads to that folder appear in the share automatically.
  //                 Deletions disappear.
  //   • selection — frozen snapshot of a specific list of videoIds. Used
  //                 when sharing an ad-hoc multi-select from the grid.
  /**
   * Read-only / edit-by-link share for the legacy embedded
   * `project.contract`. Lets the agency hand a client a URL they can
   * open without an account to view (`role: "review"`) or co-edit
   * (`role: "edit"`) the contract. Opaque token authenticates the
   * request — no other claim is needed.
   */
  contractShareLinks: defineTable({
    projectId: v.id("projects"),
    token: v.string(),
    role: v.union(v.literal("review"), v.literal("edit")),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    expiresAt: v.optional(v.number()),
    revokedAt: v.optional(v.number()),
  })
    .index("by_token", ["token"])
    .index("by_project", ["projectId"]),

  shareBundles: defineTable({
    projectId: v.id("projects"),
    name: v.string(),
    // `project` kind shares the WHOLE project root — every video, every
    // folder, every nested file. The bundle row carries no folderId or
    // videoIds; resolveBundleVideos returns all non-deleted videos
    // under the projectId.
    kind: v.union(
      v.literal("folder"),
      v.literal("selection"),
      v.literal("project"),
    ),
    folderId: v.optional(v.id("folders")),
    videoIds: v.optional(v.array(v.id("videos"))),
    // Notion-style per-share header. Optional; set via shareBundles.setHeader.
    // coverImageS3Key points at a private bucket object served through a signed
    // URL on the share page.
    coverImageS3Key: v.optional(v.string()),
    headerTitle: v.optional(v.string()),
    headerDescription: v.optional(v.string()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_folder", ["folderId"]),

  // A share link points to EITHER a single videoId OR a bundleId — exactly
  // one is set. The two-shape pattern keeps the single-video path simple and
  // unchanged for legacy data. The grant + paywall mechanics are identical
  // for both shapes; the difference is whether the share page renders a
  // single-player view or a folder-style index.
  shareLinks: defineTable({
    videoId: v.optional(v.id("videos")),
    bundleId: v.optional(v.id("shareBundles")),
    token: v.string(),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    expiresAt: v.optional(v.number()),
    allowDownload: v.boolean(),
    password: v.optional(v.string()),
    passwordHash: v.optional(v.string()),
    failedAccessAttempts: v.optional(v.number()),
    lockedUntil: v.optional(v.number()),
    viewCount: v.number(),
    // Paywall — if set, viewers see the watermarked preview asset until they
    // pay, then their grant gets paidAt set and the full asset is unlocked.
    paywall: v.optional(
      v.object({
        priceCents: v.number(),
        currency: v.string(),
        description: v.optional(v.string()),
      })
    ),
    // Optional hint for who this link is for. Used in the watermark on the
    // preview asset and prefilled in Stripe Checkout. NOT a security boundary.
    clientLabel: v.optional(v.string()),
    clientEmail: v.optional(v.string()),
    // Drive-style access control (Phase 3). Missing fields fall back to the
    // legacy behavior: anyone-with-the-link, commenter role, comments on.
    //  • generalAccess "anyone"  → anyone with the link gets `defaultRole`.
    //  • generalAccess "invite"  → only signed-in users whose email is in
    //    shareInvites (or the owner) may open the link; they get the invite's
    //    role. This is a real security boundary, enforced in issueAccessGrant.
    generalAccess: v.optional(
      v.union(v.literal("anyone"), v.literal("invite")),
    ),
    defaultRole: v.optional(
      v.union(
        v.literal("viewer"),
        v.literal("commenter"),
        v.literal("editor"),
      ),
    ),
    // Per-link permission toggles (Frame.io-style). commentsEnabled gates the
    // comment composer regardless of role; showAllVersions is stored for the
    // share page's version UI. Downloads continue to use `allowDownload`.
    commentsEnabled: v.optional(v.boolean()),
    showAllVersions: v.optional(v.boolean()),
    // For invite-only links: workspace members of the link's owning team get
    // in by default (they already have dashboard access to the project). The
    // owner can turn this off to make the link strictly invite-list-only.
    // Missing/true → team members allowed; false → invite list only.
    allowTeamAccess: v.optional(v.boolean()),
  })
    .index("by_token", ["token"])
    .index("by_video", ["videoId"])
    .index("by_bundle", ["bundleId"]),

  // Per-email access grants for invite-only share links. The email is stored
  // lowercased; a viewer is matched by their signed-in Clerk email. Each row
  // carries the role that email receives on the link.
  shareInvites: defineTable({
    shareLinkId: v.id("shareLinks"),
    email: v.string(),
    role: v.union(
      v.literal("viewer"),
      v.literal("commenter"),
      v.literal("editor"),
    ),
    invitedByClerkId: v.string(),
    invitedByName: v.string(),
    createdAt: v.number(),
  })
    .index("by_share_link", ["shareLinkId"])
    .index("by_link_and_email", ["shareLinkId", "email"]),

  shareAccessGrants: defineTable({
    shareLinkId: v.id("shareLinks"),
    token: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    // Paywall unlock state. paidAt is the source of truth for "this grant has
    // paid and may stream the full-res asset / download." paymentId points to
    // the payments row so refunds can revoke access by clearing paidAt.
    paidAt: v.optional(v.number()),
    paymentId: v.optional(v.id("payments")),
    // Forensic capture for leak attribution. Set on grant issuance from the
    // signed-in identity + request headers proxied by the share page. None of
    // these are required (anonymous viewer with privacy extensions still gets
    // a grant) but together they're enough to answer "which of these five
    // recipients leaked this clip?" when the burned-in watermark only shows
    // a per-link label. viewerIpHash uses sha256(ip + dailySalt) so we keep
    // the privacy boundary (no raw IPs at rest) while still being able to
    // group repeated views from the same client.
    viewerClerkId: v.optional(v.string()),
    viewerEmail: v.optional(v.string()),
    viewerIpHash: v.optional(v.string()),
    viewerUserAgent: v.optional(v.string()),
    viewerReferrer: v.optional(v.string()),
    // Access role resolved at issuance (Phase 3). Missing = legacy grant;
    // readers treat it as "commenter" for backward compatibility.
    role: v.optional(
      v.union(
        v.literal("viewer"),
        v.literal("commenter"),
        v.literal("editor"),
      ),
    ),
  })
    .index("by_token", ["token"])
    .index("by_share_link", ["shareLinkId"])
    .index("by_viewer_email", ["viewerEmail"]),

  // Per-transaction payment records. One row per Stripe Checkout Session.
  // Either shareLinkId (share-link paywall) OR videoId-only (Canva-style
  // per-video paywall) is set. videoId is always set so we can look up
  // "has anyone with this email paid for this video?" regardless of path.
  payments: defineTable({
    shareLinkId: v.optional(v.id("shareLinks")),
    grantId: v.optional(v.id("shareAccessGrants")),
    teamId: v.id("teams"),
    videoId: v.id("videos"),
    clientEmail: v.optional(v.string()),
    amountCents: v.number(),
    currency: v.string(),
    stripeCheckoutSessionId: v.string(),
    stripePaymentIntentId: v.optional(v.string()),
    stripeConnectAccountId: v.string(),
    applicationFeeAmountCents: v.optional(v.number()),
    status: v.union(
      v.literal("pending"),
      v.literal("succeeded"),
      v.literal("refunded"),
      v.literal("failed")
    ),
    paidAt: v.optional(v.number()),
    refundedAt: v.optional(v.number()),
  })
    .index("by_share_link", ["shareLinkId"])
    .index("by_grant", ["grantId"])
    .index("by_team", ["teamId"])
    .index("by_video", ["videoId"])
    .index("by_checkout_session", ["stripeCheckoutSessionId"])
    .index("by_payment_intent", ["stripePaymentIntentId"]),

  // Folder-as-version model for the desktop sync app. Editors name folders
  // however they normally would (final_v12, color_pass_b, etc.); the row
  // captures that name as `folderName` and the S3 prefix is computed from
  // it. `isLatest` is the pointer the desktop app + viewers read to decide
  // which folder is the current canonical version. `versionNumber` stays
  // around purely for ordering / display in the desktop list.
  // Real-time collaborative state for the contract editor. One row per
  // project. Stores the Yjs document as a base64-encoded binary blob —
  // Yjs handles all the conflict-free merging, we just persist the merged
  // result and broadcast it to every subscriber via Convex's reactive
  // query layer.
  //
  // Tradeoff: storing the FULL Yjs state on every update means rows grow
  // over time. Yjs has built-in garbage collection so the size stays
  // bounded in practice (rejected ops + tombstones get compacted). We
  // can add explicit `Y.mergeUpdates` snapshotting later if rows get fat.
  contractDocs: defineTable({
    projectId: v.id("projects"),
    /** base64(Y.encodeStateAsUpdate(yDoc)) */
    yjsState: v.string(),
    lastEditedAt: v.optional(v.number()),
    lastEditedBy: v.optional(v.string()),
  }).index("by_project", ["projectId"]),

  // Timeline snapshots — lawn's vit-style version control for NLE timelines.
  //
  // Each snapshot is a point-in-time capture of a Resolve / Premiere project,
  // serialized into domain-split JSON (cuts / color / audio / effects /
  // markers / metadata). Storing each domain as its own JSON string means
  // future branching can do per-domain 3-way merges (an editor branch only
  // conflicts on cuts.json, a colorist branch only on color.json — the
  // workflow vit's data model is built around).
  //
  // `fcpxml` keeps the source-of-truth export from Resolve so we can
  // round-trip back to the NLE losslessly. The domain JSONs are derived
  // views over that.
  timelineSnapshots: defineTable({
    teamId: v.id("teams"),
    projectId: v.id("projects"),
    // Optional cross-link to the folder version that this snapshot was
    // pushed alongside. Lets the desktop sync app's version dropdown
    // surface "timeline state for this folder."
    versionId: v.optional(v.id("projectVersions")),
    // Domain-split JSON payloads. Stored as strings to avoid Convex
    // value-size limits on deeply nested generated content.
    cuts: v.string(),
    color: v.string(),
    audio: v.string(),
    effects: v.string(),
    markers: v.string(),
    metadata: v.string(),
    // Raw FCPXML export from the NLE — source of truth for re-import.
    // Optional because future Premiere ingest may go through .prproj XML
    // instead of FCPXML.
    fcpxml: v.optional(v.string()),
    // Git-like branch / parent linkage. Default branch is "main".
    branch: v.string(),
    parentSnapshotId: v.optional(v.id("timelineSnapshots")),
    message: v.string(),
    // Resolve / Premiere project + timeline IDs so the plugin can match
    // snapshots back to NLE state when restoring.
    sourceProjectId: v.optional(v.string()),
    sourceTimelineId: v.optional(v.string()),
    // Who pushed it. clerkId is optional because the Resolve plugin
    // authenticates via the team's plugin token, not a Clerk identity.
    createdByClerkId: v.optional(v.string()),
    createdByName: v.string(),
    source: v.union(
      v.literal("resolve"),
      v.literal("premiere"),
      v.literal("manual"),
    ),
    // Size hints for the UI.
    sizeBytes: v.optional(v.number()),
  })
    .index("by_project", ["projectId"])
    .index("by_project_branch", ["projectId", "branch"])
    .index("by_version", ["versionId"])
    .index("by_team", ["teamId"]),

  /**
   * Account-level subscription. One per Clerk user (the `ownerClerkId`).
   * Pricing is flat-base + per-seat-overage: the user pays `baseCents`
   * each month for `includedSeats` collaborators, and `perSeatCents`
   * for each seat beyond that. A "seat" is a distinct
   * teamMember.userClerkId across all teams the owner participates
   * in (computed; not stored).
   *
   * This replaces per-team `teams.plan` for SaaS billing. The
   * `teams.plan` field stays for now to ease migration, but the
   * sidebar's "Billing & usage" link resolves here.
   */
  workspaceSubscriptions: defineTable({
    ownerClerkId: v.string(),
    plan: v.string(),
    status: v.union(
      v.literal("none"),
      v.literal("trialing"),
      v.literal("active"),
      v.literal("past_due"),
      v.literal("canceled"),
    ),
    baseCents: v.number(),
    perSeatCents: v.number(),
    includedSeats: v.number(),
    currency: v.string(),
    currentPeriodEnd: v.optional(v.number()),
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    canceledAt: v.optional(v.number()),
    // Enterprise pay-as-you-go: separate metered Stripe Price IDs for
    // storage / egress / seats / transcription. Only populated when
    // `plan === "enterprise"`; flat-tier subs leave this undefined.
    stripeMeterIds: v.optional(
      v.object({
        storage: v.string(),
        egress: v.string(),
        seats: v.string(),
        transcription: v.string(),
      }),
    ),
  })
    .index("by_owner", ["ownerClerkId"])
    .index("by_stripe_customer", ["stripeCustomerId"])
    .index("by_stripe_subscription", ["stripeSubscriptionId"]),

  /**
   * Per-billing-period usage tally for enterprise pay-as-you-go
   * subscribers. We bump these locally as work happens (egress on a
   * download, transcribed minutes when Mux returns a finished track,
   * storage as a daily snapshot) and push the deltas to Stripe via the
   * Meter Events API in a daily cron.
   *
   * `lastReportedAt` is the most recent successful Stripe report — used
   * to compute the delta since the last push so retries don't double-
   * count. The local row is the source of truth; Stripe is a write-only
   * mirror.
   */
  usageMeters: defineTable({
    workspaceOwnerClerkId: v.string(),
    periodStart: v.number(),
    periodEnd: v.number(),
    storageBytesGbMonths: v.number(),
    egressBytesGb: v.number(),
    seatCount: v.number(),
    transcribedMinutes: v.number(),
    lastReportedAt: v.optional(v.number()),
  })
    .index("by_owner", ["workspaceOwnerClerkId"])
    .index("by_owner_period", ["workspaceOwnerClerkId", "periodStart"]),

  /**
   * Multi-contract container, native to snip. Replaces the singleton
   * `projects.contract` embedded field, which stays for one release as
   * a read-fallback during migration (see contractsBackfill.ts). A
   * project can have an unbounded number of these — typical agency
   * relationships need a master agreement, per-engagement SOWs, an NDA
   * for new collaborators, etc.
   *
   * Designed to support a Documenso-equivalent e-sign flow in-product,
   * without calling out to an external API:
   *   • `contentHtml` is the editable contract body (Tiptap output).
   *   • `signablePdfS3Key` holds the rendered PDF generated when the
   *     author hits "Send for signature" (R2-cached).
   *   • `signedPdfS3Key` holds the final stamped + audited PDF after
   *     all signers complete.
   *   • The state machine (`status`) is enforced by the mutations in
   *     `contractsTable.ts`.
   */
  contracts: defineTable({
    projectId: v.id("projects"),
    teamId: v.id("teams"),
    title: v.string(),
    kind: v.union(
      v.literal("master"),
      v.literal("sow"),
      v.literal("nda"),
      v.literal("release"),
      v.literal("custom"),
    ),
    // Unified editor mode. "contract" (default when absent) shows the signing
    // surface (recipients, fields, send, audit, certificate). "document" is a
    // plain doc — same editor, signing hidden. Toggleable in the editor header.
    docType: v.optional(v.union(v.literal("contract"), v.literal("document"))),
    // Editable body (Tiptap HTML) + the wizard-generated clauses (same
    // shape as projects.contract.clauses).
    contentHtml: v.string(),
    clauses: v.optional(
      v.array(
        v.object({
          id: v.string(),
          sectionKey: v.string(),
          title: v.string(),
          bodyHtml: v.string(),
          state: v.union(
            v.literal("draft"),
            v.literal("pending"),
            v.literal("accepted"),
            v.literal("disputed"),
          ),
          required: v.boolean(),
          order: v.number(),
          sourceAnswerId: v.optional(v.string()),
          proposedBody: v.optional(v.string()),
        }),
      ),
    ),
    projectType: v.optional(
      v.union(
        v.literal("logo_design"),
        v.literal("video_production"),
        v.literal("web_design"),
        v.literal("photography"),
        v.literal("brand_identity"),
        v.literal("copywriting"),
        v.literal("music"),
        v.literal("animation"),
        v.literal("custom"),
      ),
    ),
    wizardAnswers: v.optional(v.string()),
    priceCents: v.optional(v.number()),
    currency: v.optional(v.string()),
    deadline: v.optional(v.string()),
    clientName: v.optional(v.string()),
    clientEmail: v.optional(v.string()),
    docxS3Key: v.optional(v.string()),
    originalFilename: v.optional(v.string()),
    lastSavedAt: v.optional(v.number()),
    // Signing artefacts.
    signablePdfS3Key: v.optional(v.string()),
    signedPdfS3Key: v.optional(v.string()),
    // Self-contained signed package (HTML: frozen body + signature blocks +
    // Certificate of Completion) written to R2 on completion. Printable to PDF
    // by anyone; carries the content hash so integrity is independently
    // verifiable. True server-side PDF render is a follow-up (no renderer in
    // the Convex runtime).
    signedPackageS3Key: v.optional(v.string()),
    // Court-admissibility: the exact body frozen at send time + its SHA-256.
    // "Association with the record" + tamper-evidence (ESIGN/UETA) — what the
    // signers agreed to, immutable, verifiable by re-hashing. See
    // plans/court-signing.md.
    frozenContentHtml: v.optional(v.string()),
    contentHash: v.optional(v.string()),
    status: v.union(
      v.literal("draft"),
      v.literal("pending"),
      v.literal("completed"),
      v.literal("declined"),
      v.literal("voided"),
      v.literal("expired"),
    ),
    sentForSignatureAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    expiresAt: v.optional(v.number()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    deletedAt: v.optional(v.number()),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_status", ["projectId", "status"])
    .index("by_status", ["status"]),

  /**
   * Recipients of a contract. Each row carries an opaque signing-link
   * token that maps an external visitor to a single recipient; the
   * token is checked on every public sign route hit.
   *
   * `order` controls sequential signing (1..n). When `order=1` signs,
   * the mutation flips order=2 to status=pending; this lets a CEO
   * sign first, then the client.
   */
  contractRecipients: defineTable({
    contractId: v.id("contracts"),
    projectId: v.id("projects"),
    name: v.string(),
    email: v.string(),
    role: v.union(
      v.literal("signer"),
      v.literal("approver"),
      v.literal("viewer"),
      v.literal("cc"),
    ),
    order: v.number(),
    token: v.string(),
    tokenExpiresAt: v.number(),
    status: v.union(
      v.literal("pending"),
      v.literal("viewed"),
      v.literal("signed"),
      v.literal("declined"),
    ),
    signedAt: v.optional(v.number()),
    viewedAt: v.optional(v.number()),
    signatureDataUrl: v.optional(v.string()),
    typedSignatureName: v.optional(v.string()),
    signedIp: v.optional(v.string()),
    signedUserAgent: v.optional(v.string()),
    // ESIGN consent to do business electronically — required before a
    // signature is legally binding. Timestamp of the affirmative checkbox.
    consentedAt: v.optional(v.number()),
    // Email OTP identity verification. Hash = SHA-256(`${token}:${code}`); the
    // plaintext code is only emailed, never stored. Cleared after a successful
    // sign. When present, the sign mutation requires a matching, unexpired code.
    otpCodeHash: v.optional(v.string()),
    otpExpiresAt: v.optional(v.number()),
  })
    .index("by_contract", ["contractId"])
    .index("by_token", ["token"])
    .index("by_contract_and_order", ["contractId", "order"]),

  /**
   * Fields placed by the contract author on the PDF, to be filled in
   * by recipients at sign time. Coordinates are normalized to 0..1 of
   * page width/height so they survive re-renders at different
   * resolutions.
   *
   * v1 wires the typed-signature flow only. The full drag-and-drop
   * field placement editor is v2 work — until then, only one implicit
   * "signature" field per recipient is required.
   */
  contractFields: defineTable({
    contractId: v.id("contracts"),
    recipientId: v.id("contractRecipients"),
    type: v.union(
      v.literal("signature"),
      v.literal("initials"),
      v.literal("date"),
      v.literal("text"),
      v.literal("checkbox"),
      v.literal("name"),
      v.literal("email"),
    ),
    pageIndex: v.number(),
    x: v.number(),
    y: v.number(),
    width: v.number(),
    height: v.number(),
    required: v.boolean(),
    value: v.optional(v.string()),
  })
    .index("by_contract", ["contractId"])
    .index("by_recipient", ["recipientId"]),

  /**
   * Append-only audit log for each contract. Captures every meaningful
   * action — created, sent, viewed, field_filled, signed, declined,
   * voided, reminder_sent, completed — with the actor, IP, and UA
   * where available. Rendered into the final PDF's audit page when
   * `finalizeContract` runs.
   */
  contractAuditEvents: defineTable({
    contractId: v.id("contracts"),
    recipientId: v.optional(v.id("contractRecipients")),
    action: v.union(
      v.literal("created"),
      v.literal("sent"),
      v.literal("viewed"),
      v.literal("consented"),
      v.literal("field_filled"),
      v.literal("signed"),
      v.literal("declined"),
      v.literal("voided"),
      v.literal("reminder_sent"),
      v.literal("completed"),
    ),
    actorName: v.optional(v.string()),
    actorEmail: v.optional(v.string()),
    ip: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    metadata: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_contract", ["contractId"]),

  /**
   * Contract comments. Project-scoped (one stream per contract), with
   * optional anchor text so the UI can show "commented on: '<quoted
   * paragraph>'" without a full prosemirror anchor model. Resolved
   * comments stay on the row so threads can be re-opened; the UI just
   * filters them out of the unresolved view.
   */
  contractComments: defineTable({
    projectId: v.id("projects"),
    authorClerkId: v.string(),
    authorName: v.string(),
    authorAvatarUrl: v.optional(v.string()),
    body: v.string(),
    anchorText: v.optional(v.string()),
    resolvedAt: v.optional(v.number()),
    resolvedByName: v.optional(v.string()),
  }).index("by_project", ["projectId"]),

  /**
   * Contract version snapshots. Each row is a full point-in-time
   * snapshot of the contract HTML + the wizard answers blob, taken
   * either explicitly via "Save version" or automatically on big
   * milestones (Sent for signature, Signed). Restore replays the
   * snapshot into the live contract.
   */
  contractVersions: defineTable({
    projectId: v.id("projects"),
    versionNumber: v.number(),
    label: v.optional(v.string()),
    contentHtml: v.string(),
    wizardAnswers: v.optional(v.string()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_version", ["projectId", "versionNumber"]),

  /**
   * Unified version model — foundation for "every reviewable item runs
   * the same version stack." Subsumes the two legacy mechanisms:
   *   - video lineage (videos.lineageId / isCurrentVersion) → kind "asset"
   *   - contractVersions snapshots                          → kind "doc"
   *
   * `lineageKey` is the stable identity of the logical item, kept as a
   * string so it isn't pinned to one table's Id type while the legacy
   * systems remain authoritative:
   *   - asset: the lineage-root videoId
   *   - doc:   the projectId (until documents become first-class items)
   *
   * This phase only DUAL-WRITES here from the existing create paths;
   * reads still flow through the legacy code, so nothing breaks. Later
   * phases flip reads onto this table and retire the old fields/table.
   */
  itemVersions: defineTable({
    lineageKey: v.string(),
    projectId: v.id("projects"),
    kind: v.union(v.literal("asset"), v.literal("doc")),
    versionNumber: v.number(),
    isCurrent: v.boolean(),
    label: v.optional(v.string()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    // asset → the videos row that holds this version's media
    videoId: v.optional(v.id("videos")),
    // doc → point-in-time content snapshot
    contentHtml: v.optional(v.string()),
    wizardAnswers: v.optional(v.string()),
  })
    .index("by_lineage", ["lineageKey"])
    .index("by_project", ["projectId"]),

  /**
   * Soft-deleted contracts. When a user "deletes" a contract from a
   * project we snapshot the whole contract object here and clear the
   * project's `contract` field. Restore copies the snapshot back to
   * the project and removes the row; purge just removes the row.
   *
   * teamId is denormalized so the trash query can scope by team
   * membership without re-fetching the parent project (which may
   * itself be soft-deleted).
   */
  trashedContracts: defineTable({
    projectId: v.id("projects"),
    teamId: v.id("teams"),
    projectName: v.string(),
    // Raw contract blob, identical shape to `projects.contract`.
    contract: v.any(),
    deletedAt: v.number(),
    deletedByClerkId: v.string(),
    deletedByName: v.optional(v.string()),
  })
    .index("by_project", ["projectId"])
    .index("by_team", ["teamId"])
    .index("by_team_and_deleted_at", ["teamId", "deletedAt"]),

  /**
   * Per-folder team permission grants. Each row scopes a path prefix
   * (e.g. "projects/red-bull-spring/raw/") to a set of roles and/or
   * specific user clerk IDs. The snip Desktop app's ACL panel uses
   * `folderPermissions:checkAccess` to gate visibility of folders in
   * the team-shared mount.
   *
   * This table records *intent*. Actual S3-side enforcement (scoped
   * STS credentials vended per session) is a separate infrastructure
   * concern that isn't wired up yet — the data layer is the
   * prerequisite for that future work, and the UI surfaces the
   * intended grants to the team admin.
   */
  folderPermissions: defineTable({
    teamId: v.id("teams"),
    // Path prefix within the team's bucket / project tree. Matched as
    // a string prefix in checkAccess, with a trailing-separator guard
    // to avoid sibling-folder leakage.
    pathPrefix: v.string(),
    // Roles that get automatic access. Empty array means role-based
    // access is disabled and the grant relies on allowedClerkIds.
    allowedRoles: v.array(v.string()),
    // Explicit user grants (Clerk subject IDs). Layers on top of
    // allowedRoles — either a role match OR a clerkId match grants
    // access.
    allowedClerkIds: v.array(v.string()),
    // Human note shown in the admin UI ("Raw masters — sound team only").
    note: v.optional(v.string()),
    createdAt: v.number(),
    createdByClerkId: v.string(),
  })
    .index("by_team", ["teamId"])
    .index("by_team_and_prefix", ["teamId", "pathPrefix"]),

  /**
   * Live "who has what file open" state from the snip Desktop app.
   * The desktop main process polls `lsof` against the mount path every
   * few seconds and upserts the row for its `clientId` (a stable
   * per-install ID). Rows older than ~30s are stale and the read query
   * filters them out; we don't TTL because Convex doesn't have native
   * TTL — stale rows are overwritten on the next push, or cleared on
   * graceful shutdown via `desktopPresence:clearLocks`.
   */
  desktopFileLocks: defineTable({
    clientId: v.string(),
    userClerkId: v.string(),
    userName: v.optional(v.string()),
    // Project the mount is rooted under. Optional because the desktop
    // app can run before the user picks an active project.
    projectId: v.optional(v.id("projects")),
    teamId: v.optional(v.id("teams")),
    mountPath: v.string(),
    files: v.array(
      v.object({
        // Path relative to mountPath.
        path: v.string(),
        // The process that has the file open, e.g. "Adobe Premiere Pro 2024".
        process: v.optional(v.string()),
        pid: v.optional(v.number()),
      }),
    ),
    lastSeen: v.number(),
  })
    .index("by_client", ["clientId"])
    .index("by_project", ["projectId"])
    .index("by_team", ["teamId"]),

  projectVersions: defineTable({
    projectId: v.id("projects"),
    teamId: v.id("teams"),
    // Optional only so older rows pushed before this field existed don't
    // block schema upgrade. All new rows set it; readers fall back to
    // `v${versionNumber}` when missing.
    folderName: v.optional(v.string()),
    versionNumber: v.number(),
    label: v.optional(v.string()),
    notes: v.optional(v.string()),
    s3Prefix: v.string(),
    sizeBytes: v.optional(v.number()),
    fileCount: v.optional(v.number()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    isLatest: v.boolean(),
    // If a delivery (share link) was created from this version, we track it
    // here so payment unlocks the right artifact even if a newer version exists.
    deliveredShareLinkId: v.optional(v.id("shareLinks")),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_folder", ["projectId", "folderName"])
    .index("by_project_and_version", ["projectId", "versionNumber"])
    .index("by_project_latest", ["projectId", "isLatest"])
    .index("by_team", ["teamId"]),

  /**
   * Global full-text search index. One denormalized row per searchable
   * thing — a video/file, a contract document (its plaintext + clause
   * bodies), a comment, and (Part B, later) a video-frame caption —
   * fed by best-effort dual-writes from the content mutations plus a
   * `search.reindexAll` backfill. The ⌘K palette queries this so a word
   * *inside* a document or a comment is findable, not just titles.
   */
  searchableContent: defineTable({
    teamId: v.id("teams"),
    teamSlug: v.string(),
    projectId: v.optional(v.id("projects")),
    videoId: v.optional(v.id("videos")),
    kind: v.union(
      v.literal("video"),
      v.literal("document"),
      v.literal("comment"),
      v.literal("frame"),
      v.literal("transcript"),
    ),
    // Stable identity of the source row (videoId / projectId / commentId
    // / `${videoId}:${frameSec}`) so dual-writes can upsert in place.
    refId: v.string(),
    title: v.string(),
    contextLabel: v.string(),
    text: v.string(),
  })
    .index("by_ref", ["kind", "refId"])
    .index("by_video", ["videoId"])
    .searchIndex("by_text", {
      searchField: "text",
      filterFields: ["teamId", "kind"],
    }),

  /**
   * Desktop device-pairing. The desktop app generates a high-entropy
   * `code`, opens the web app's /connect-desktop?code=… (where the user
   * is signed in via Clerk), and polls. The web page approves: we mint a
   * single-use Clerk *sign-in token* for the signed-in user and stash it
   * here. The desktop polls once more, receives the sign-in token + the
   * storage bootstrap, redeems the ticket with Clerk JS to establish its
   * own durable session, and never touches credentials again.
   *
   * Rows are short-lived (10-min expiry) and single-use — the sign-in
   * token is cleared the moment the desktop reads it.
   */
  desktopPairings: defineTable({
    code: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("consumed"),
      v.literal("expired"),
    ),
    createdAt: v.number(),
    expiresAt: v.number(),
    deviceLabel: v.optional(v.string()),
    userClerkId: v.optional(v.string()),
    userName: v.optional(v.string()),
    // One-time Clerk sign-in token — present only between approve and the
    // desktop's next poll, then nulled.
    signInToken: v.optional(v.string()),
  }).index("by_code", ["code"]),

  /**
   * Per-user email notification preferences (Settings → Notifications).
   * Absent row = defaults: comment replies + contract-signed ON, upload
   * completion OFF (mirrors the original toggle defaults).
   */
  notificationPrefs: defineTable({
    userClerkId: v.string(),
    commentReply: v.boolean(),
    contractSigned: v.boolean(),
    uploadFinished: v.boolean(),
  }).index("by_user", ["userClerkId"]),
});
