/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MonoRouteImport } from './routes/mono'
import { Route as ConnectDesktopRouteImport } from './routes/connect-desktop'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WatchPublicIdRouteImport } from './routes/watch.$publicId'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ForVideoEditorsRouteImport } from './routes/for.video-editors'
import { Route as ForAgenciesRouteImport } from './routes/for.agencies'
import { Route as DashboardTrashRouteImport } from './routes/dashboard/trash'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardTeamSlugRouteImport } from './routes/dashboard/$teamSlug'
import { Route as CompareWipsterRouteImport } from './routes/compare.wipster'
import { Route as CompareLucidlinkRouteImport } from './routes/compare.lucidlink'
import { Route as CompareFrameioRouteImport } from './routes/compare.frameio'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as DashboardTeamSlugIndexRouteImport } from './routes/dashboard/$teamSlug.index'
import { Route as DashboardTeamSlugSettingsRouteImport } from './routes/dashboard/$teamSlug.settings'
import { Route as DashboardTeamSlugInvoicesRouteImport } from './routes/dashboard/$teamSlug.invoices'
import { Route as DashboardTeamSlugProjectIdRouteImport } from './routes/dashboard/$teamSlug.$projectId'
import { Route as DashboardTeamSlugSettingsIndexRouteImport } from './routes/dashboard/$teamSlug.settings.index'
import { Route as DashboardTeamSlugProjectIdIndexRouteImport } from './routes/dashboard/$teamSlug.$projectId.index'
import { Route as DashboardTeamSlugSettingsPayoutsRouteImport } from './routes/dashboard/$teamSlug.settings.payouts'
import { Route as DashboardTeamSlugSettingsFoldersRouteImport } from './routes/dashboard/$teamSlug.settings.folders'
import { Route as DashboardTeamSlugInvoicesInvoiceIdRouteImport } from './routes/dashboard/$teamSlug.invoices_.$invoiceId'
import { Route as DashboardTeamSlugProjectIdPlaybackLabRouteImport } from './routes/dashboard/$teamSlug.$projectId.playback-lab'
import { Route as DashboardTeamSlugProjectIdEditorRouteImport } from './routes/dashboard/$teamSlug.$projectId.editor'
import { Route as DashboardTeamSlugProjectIdContractRouteImport } from './routes/dashboard/$teamSlug.$projectId.contract'
import { Route as DashboardTeamSlugProjectIdVideoIdRouteImport } from './routes/dashboard/$teamSlug.$projectId.$videoId'
import { Route as DashboardTeamSlugProjectIdDocContractIdRouteImport } from './routes/dashboard/$teamSlug.$projectId.doc.$contractId'
import { Route as DashboardTeamSlugProjectIdContractContractIdRouteImport } from './routes/dashboard/$teamSlug.$projectId.contract_.$contractId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MonoRoute = MonoRouteImport.update({
  id: '/mono',
  path: '/mono',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectDesktopRoute = ConnectDesktopRouteImport.update({
  id: '/connect-desktop',
  path: '/connect-desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const WatchPublicIdRoute = WatchPublicIdRouteImport.update({
  id: '/watch/$publicId',
  path: '/watch/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVideoEditorsRoute = ForVideoEditorsRouteImport.update({
  id: '/for/video-editors',
  path: '/for/video-editors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgenciesRoute = ForAgenciesRouteImport.update({
  id: '/for/agencies',
  path: '/for/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamSlugRoute = DashboardTeamSlugRouteImport.update({
  id: '/$teamSlug',
  path: '/$teamSlug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CompareWipsterRoute = CompareWipsterRouteImport.update({
  id: '/compare/wipster',
  path: '/compare/wipster',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareLucidlinkRoute = CompareLucidlinkRouteImport.update({
  id: '/compare/lucidlink',
  path: '/compare/lucidlink',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFrameioRoute = CompareFrameioRouteImport.update({
  id: '/compare/frameio',
  path: '/compare/frameio',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamSlugIndexRoute = DashboardTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeamSlugRoute,
} as any)
const DashboardTeamSlugSettingsRoute =
  DashboardTeamSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardTeamSlugRoute,
  } as any)
const DashboardTeamSlugInvoicesRoute =
  DashboardTeamSlugInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => DashboardTeamSlugRoute,
  } as any)
const DashboardTeamSlugProjectIdRoute =
  DashboardTeamSlugProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardTeamSlugRoute,
  } as any)
const DashboardTeamSlugSettingsIndexRoute =
  DashboardTeamSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeamSlugSettingsRoute,
  } as any)
const DashboardTeamSlugProjectIdIndexRoute =
  DashboardTeamSlugProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugSettingsPayoutsRoute =
  DashboardTeamSlugSettingsPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => DashboardTeamSlugSettingsRoute,
  } as any)
const DashboardTeamSlugSettingsFoldersRoute =
  DashboardTeamSlugSettingsFoldersRouteImport.update({
    id: '/folders',
    path: '/folders',
    getParentRoute: () => DashboardTeamSlugSettingsRoute,
  } as any)
const DashboardTeamSlugInvoicesInvoiceIdRoute =
  DashboardTeamSlugInvoicesInvoiceIdRouteImport.update({
    id: '/invoices_/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => DashboardTeamSlugRoute,
  } as any)
const DashboardTeamSlugProjectIdPlaybackLabRoute =
  DashboardTeamSlugProjectIdPlaybackLabRouteImport.update({
    id: '/playback-lab',
    path: '/playback-lab',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugProjectIdEditorRoute =
  DashboardTeamSlugProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugProjectIdContractRoute =
  DashboardTeamSlugProjectIdContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugProjectIdVideoIdRoute =
  DashboardTeamSlugProjectIdVideoIdRouteImport.update({
    id: '/$videoId',
    path: '/$videoId',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugProjectIdDocContractIdRoute =
  DashboardTeamSlugProjectIdDocContractIdRouteImport.update({
    id: '/doc/$contractId',
    path: '/doc/$contractId',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)
const DashboardTeamSlugProjectIdContractContractIdRoute =
  DashboardTeamSlugProjectIdContractContractIdRouteImport.update({
    id: '/contract_/$contractId',
    path: '/contract/$contractId',
    getParentRoute: () => DashboardTeamSlugProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/connect-desktop': typeof ConnectDesktopRoute
  '/mono': typeof MonoRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/compare/frameio': typeof CompareFrameioRoute
  '/compare/lucidlink': typeof CompareLucidlinkRoute
  '/compare/wipster': typeof CompareWipsterRoute
  '/dashboard/$teamSlug': typeof DashboardTeamSlugRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/video-editors': typeof ForVideoEditorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pay/$token': typeof PayTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/sign/$token': typeof SignTokenRoute
  '/watch/$publicId': typeof WatchPublicIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamSlug/$projectId': typeof DashboardTeamSlugProjectIdRouteWithChildren
  '/dashboard/$teamSlug/invoices': typeof DashboardTeamSlugInvoicesRoute
  '/dashboard/$teamSlug/settings': typeof DashboardTeamSlugSettingsRouteWithChildren
  '/dashboard/$teamSlug/': typeof DashboardTeamSlugIndexRoute
  '/dashboard/$teamSlug/$projectId/$videoId': typeof DashboardTeamSlugProjectIdVideoIdRoute
  '/dashboard/$teamSlug/$projectId/contract': typeof DashboardTeamSlugProjectIdContractRoute
  '/dashboard/$teamSlug/$projectId/editor': typeof DashboardTeamSlugProjectIdEditorRoute
  '/dashboard/$teamSlug/$projectId/playback-lab': typeof DashboardTeamSlugProjectIdPlaybackLabRoute
  '/dashboard/$teamSlug/invoices/$invoiceId': typeof DashboardTeamSlugInvoicesInvoiceIdRoute
  '/dashboard/$teamSlug/settings/folders': typeof DashboardTeamSlugSettingsFoldersRoute
  '/dashboard/$teamSlug/settings/payouts': typeof DashboardTeamSlugSettingsPayoutsRoute
  '/dashboard/$teamSlug/$projectId/': typeof DashboardTeamSlugProjectIdIndexRoute
  '/dashboard/$teamSlug/settings/': typeof DashboardTeamSlugSettingsIndexRoute
  '/dashboard/$teamSlug/$projectId/contract/$contractId': typeof DashboardTeamSlugProjectIdContractContractIdRoute
  '/dashboard/$teamSlug/$projectId/doc/$contractId': typeof DashboardTeamSlugProjectIdDocContractIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-desktop': typeof ConnectDesktopRoute
  '/mono': typeof MonoRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/compare/frameio': typeof CompareFrameioRoute
  '/compare/lucidlink': typeof CompareLucidlinkRoute
  '/compare/wipster': typeof CompareWipsterRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/video-editors': typeof ForVideoEditorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pay/$token': typeof PayTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/sign/$token': typeof SignTokenRoute
  '/watch/$publicId': typeof WatchPublicIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$teamSlug/invoices': typeof DashboardTeamSlugInvoicesRoute
  '/dashboard/$teamSlug': typeof DashboardTeamSlugIndexRoute
  '/dashboard/$teamSlug/$projectId/$videoId': typeof DashboardTeamSlugProjectIdVideoIdRoute
  '/dashboard/$teamSlug/$projectId/contract': typeof DashboardTeamSlugProjectIdContractRoute
  '/dashboard/$teamSlug/$projectId/editor': typeof DashboardTeamSlugProjectIdEditorRoute
  '/dashboard/$teamSlug/$projectId/playback-lab': typeof DashboardTeamSlugProjectIdPlaybackLabRoute
  '/dashboard/$teamSlug/invoices/$invoiceId': typeof DashboardTeamSlugInvoicesInvoiceIdRoute
  '/dashboard/$teamSlug/settings/folders': typeof DashboardTeamSlugSettingsFoldersRoute
  '/dashboard/$teamSlug/settings/payouts': typeof DashboardTeamSlugSettingsPayoutsRoute
  '/dashboard/$teamSlug/$projectId': typeof DashboardTeamSlugProjectIdIndexRoute
  '/dashboard/$teamSlug/settings': typeof DashboardTeamSlugSettingsIndexRoute
  '/dashboard/$teamSlug/$projectId/contract/$contractId': typeof DashboardTeamSlugProjectIdContractContractIdRoute
  '/dashboard/$teamSlug/$projectId/doc/$contractId': typeof DashboardTeamSlugProjectIdDocContractIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/connect-desktop': typeof ConnectDesktopRoute
  '/mono': typeof MonoRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/compare/frameio': typeof CompareFrameioRoute
  '/compare/lucidlink': typeof CompareLucidlinkRoute
  '/compare/wipster': typeof CompareWipsterRoute
  '/dashboard/$teamSlug': typeof DashboardTeamSlugRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/video-editors': typeof ForVideoEditorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pay/$token': typeof PayTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/sign/$token': typeof SignTokenRoute
  '/watch/$publicId': typeof WatchPublicIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamSlug/$projectId': typeof DashboardTeamSlugProjectIdRouteWithChildren
  '/dashboard/$teamSlug/invoices': typeof DashboardTeamSlugInvoicesRoute
  '/dashboard/$teamSlug/settings': typeof DashboardTeamSlugSettingsRouteWithChildren
  '/dashboard/$teamSlug/': typeof DashboardTeamSlugIndexRoute
  '/dashboard/$teamSlug/$projectId/$videoId': typeof DashboardTeamSlugProjectIdVideoIdRoute
  '/dashboard/$teamSlug/$projectId/contract': typeof DashboardTeamSlugProjectIdContractRoute
  '/dashboard/$teamSlug/$projectId/editor': typeof DashboardTeamSlugProjectIdEditorRoute
  '/dashboard/$teamSlug/$projectId/playback-lab': typeof DashboardTeamSlugProjectIdPlaybackLabRoute
  '/dashboard/$teamSlug/invoices_/$invoiceId': typeof DashboardTeamSlugInvoicesInvoiceIdRoute
  '/dashboard/$teamSlug/settings/folders': typeof DashboardTeamSlugSettingsFoldersRoute
  '/dashboard/$teamSlug/settings/payouts': typeof DashboardTeamSlugSettingsPayoutsRoute
  '/dashboard/$teamSlug/$projectId/': typeof DashboardTeamSlugProjectIdIndexRoute
  '/dashboard/$teamSlug/settings/': typeof DashboardTeamSlugSettingsIndexRoute
  '/dashboard/$teamSlug/$projectId/contract_/$contractId': typeof DashboardTeamSlugProjectIdContractContractIdRoute
  '/dashboard/$teamSlug/$projectId/doc/$contractId': typeof DashboardTeamSlugProjectIdDocContractIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/connect-desktop'
    | '/mono'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/c/$token'
    | '/compare/frameio'
    | '/compare/lucidlink'
    | '/compare/wipster'
    | '/dashboard/$teamSlug'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/for/agencies'
    | '/for/video-editors'
    | '/invite/$token'
    | '/pay/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/sign/$token'
    | '/watch/$publicId'
    | '/dashboard/'
    | '/dashboard/$teamSlug/$projectId'
    | '/dashboard/$teamSlug/invoices'
    | '/dashboard/$teamSlug/settings'
    | '/dashboard/$teamSlug/'
    | '/dashboard/$teamSlug/$projectId/$videoId'
    | '/dashboard/$teamSlug/$projectId/contract'
    | '/dashboard/$teamSlug/$projectId/editor'
    | '/dashboard/$teamSlug/$projectId/playback-lab'
    | '/dashboard/$teamSlug/invoices/$invoiceId'
    | '/dashboard/$teamSlug/settings/folders'
    | '/dashboard/$teamSlug/settings/payouts'
    | '/dashboard/$teamSlug/$projectId/'
    | '/dashboard/$teamSlug/settings/'
    | '/dashboard/$teamSlug/$projectId/contract/$contractId'
    | '/dashboard/$teamSlug/$projectId/doc/$contractId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-desktop'
    | '/mono'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/c/$token'
    | '/compare/frameio'
    | '/compare/lucidlink'
    | '/compare/wipster'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/for/agencies'
    | '/for/video-editors'
    | '/invite/$token'
    | '/pay/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/sign/$token'
    | '/watch/$publicId'
    | '/dashboard'
    | '/dashboard/$teamSlug/invoices'
    | '/dashboard/$teamSlug'
    | '/dashboard/$teamSlug/$projectId/$videoId'
    | '/dashboard/$teamSlug/$projectId/contract'
    | '/dashboard/$teamSlug/$projectId/editor'
    | '/dashboard/$teamSlug/$projectId/playback-lab'
    | '/dashboard/$teamSlug/invoices/$invoiceId'
    | '/dashboard/$teamSlug/settings/folders'
    | '/dashboard/$teamSlug/settings/payouts'
    | '/dashboard/$teamSlug/$projectId'
    | '/dashboard/$teamSlug/settings'
    | '/dashboard/$teamSlug/$projectId/contract/$contractId'
    | '/dashboard/$teamSlug/$projectId/doc/$contractId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/connect-desktop'
    | '/mono'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/c/$token'
    | '/compare/frameio'
    | '/compare/lucidlink'
    | '/compare/wipster'
    | '/dashboard/$teamSlug'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/for/agencies'
    | '/for/video-editors'
    | '/invite/$token'
    | '/pay/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/sign/$token'
    | '/watch/$publicId'
    | '/dashboard/'
    | '/dashboard/$teamSlug/$projectId'
    | '/dashboard/$teamSlug/invoices'
    | '/dashboard/$teamSlug/settings'
    | '/dashboard/$teamSlug/'
    | '/dashboard/$teamSlug/$projectId/$videoId'
    | '/dashboard/$teamSlug/$projectId/contract'
    | '/dashboard/$teamSlug/$projectId/editor'
    | '/dashboard/$teamSlug/$projectId/playback-lab'
    | '/dashboard/$teamSlug/invoices_/$invoiceId'
    | '/dashboard/$teamSlug/settings/folders'
    | '/dashboard/$teamSlug/settings/payouts'
    | '/dashboard/$teamSlug/$projectId/'
    | '/dashboard/$teamSlug/settings/'
    | '/dashboard/$teamSlug/$projectId/contract_/$contractId'
    | '/dashboard/$teamSlug/$projectId/doc/$contractId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ConnectDesktopRoute: typeof ConnectDesktopRoute
  MonoRoute: typeof MonoRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  CTokenRoute: typeof CTokenRoute
  CompareFrameioRoute: typeof CompareFrameioRoute
  CompareLucidlinkRoute: typeof CompareLucidlinkRoute
  CompareWipsterRoute: typeof CompareWipsterRoute
  ForAgenciesRoute: typeof ForAgenciesRoute
  ForVideoEditorsRoute: typeof ForVideoEditorsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PayTokenRoute: typeof PayTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  WatchPublicIdRoute: typeof WatchPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mono': {
      id: '/mono'
      path: '/mono'
      fullPath: '/mono'
      preLoaderRoute: typeof MonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-desktop': {
      id: '/connect-desktop'
      path: '/connect-desktop'
      fullPath: '/connect-desktop'
      preLoaderRoute: typeof ConnectDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/watch/$publicId': {
      id: '/watch/$publicId'
      path: '/watch/$publicId'
      fullPath: '/watch/$publicId'
      preLoaderRoute: typeof WatchPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/video-editors': {
      id: '/for/video-editors'
      path: '/for/video-editors'
      fullPath: '/for/video-editors'
      preLoaderRoute: typeof ForVideoEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/agencies': {
      id: '/for/agencies'
      path: '/for/agencies'
      fullPath: '/for/agencies'
      preLoaderRoute: typeof ForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$teamSlug': {
      id: '/dashboard/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/dashboard/$teamSlug'
      preLoaderRoute: typeof DashboardTeamSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/compare/wipster': {
      id: '/compare/wipster'
      path: '/compare/wipster'
      fullPath: '/compare/wipster'
      preLoaderRoute: typeof CompareWipsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/lucidlink': {
      id: '/compare/lucidlink'
      path: '/compare/lucidlink'
      fullPath: '/compare/lucidlink'
      preLoaderRoute: typeof CompareLucidlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/frameio': {
      id: '/compare/frameio'
      path: '/compare/frameio'
      fullPath: '/compare/frameio'
      preLoaderRoute: typeof CompareFrameioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$teamSlug/': {
      id: '/dashboard/$teamSlug/'
      path: '/'
      fullPath: '/dashboard/$teamSlug/'
      preLoaderRoute: typeof DashboardTeamSlugIndexRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/settings': {
      id: '/dashboard/$teamSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/$teamSlug/settings'
      preLoaderRoute: typeof DashboardTeamSlugSettingsRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/invoices': {
      id: '/dashboard/$teamSlug/invoices'
      path: '/invoices'
      fullPath: '/dashboard/$teamSlug/invoices'
      preLoaderRoute: typeof DashboardTeamSlugInvoicesRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/$projectId': {
      id: '/dashboard/$teamSlug/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$teamSlug/$projectId'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/settings/': {
      id: '/dashboard/$teamSlug/settings/'
      path: '/'
      fullPath: '/dashboard/$teamSlug/settings/'
      preLoaderRoute: typeof DashboardTeamSlugSettingsIndexRouteImport
      parentRoute: typeof DashboardTeamSlugSettingsRoute
    }
    '/dashboard/$teamSlug/$projectId/': {
      id: '/dashboard/$teamSlug/$projectId/'
      path: '/'
      fullPath: '/dashboard/$teamSlug/$projectId/'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdIndexRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/settings/payouts': {
      id: '/dashboard/$teamSlug/settings/payouts'
      path: '/payouts'
      fullPath: '/dashboard/$teamSlug/settings/payouts'
      preLoaderRoute: typeof DashboardTeamSlugSettingsPayoutsRouteImport
      parentRoute: typeof DashboardTeamSlugSettingsRoute
    }
    '/dashboard/$teamSlug/settings/folders': {
      id: '/dashboard/$teamSlug/settings/folders'
      path: '/folders'
      fullPath: '/dashboard/$teamSlug/settings/folders'
      preLoaderRoute: typeof DashboardTeamSlugSettingsFoldersRouteImport
      parentRoute: typeof DashboardTeamSlugSettingsRoute
    }
    '/dashboard/$teamSlug/invoices_/$invoiceId': {
      id: '/dashboard/$teamSlug/invoices_/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/dashboard/$teamSlug/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardTeamSlugInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardTeamSlugRoute
    }
    '/dashboard/$teamSlug/$projectId/playback-lab': {
      id: '/dashboard/$teamSlug/$projectId/playback-lab'
      path: '/playback-lab'
      fullPath: '/dashboard/$teamSlug/$projectId/playback-lab'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdPlaybackLabRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/$projectId/editor': {
      id: '/dashboard/$teamSlug/$projectId/editor'
      path: '/editor'
      fullPath: '/dashboard/$teamSlug/$projectId/editor'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdEditorRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/$projectId/contract': {
      id: '/dashboard/$teamSlug/$projectId/contract'
      path: '/contract'
      fullPath: '/dashboard/$teamSlug/$projectId/contract'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdContractRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/$projectId/$videoId': {
      id: '/dashboard/$teamSlug/$projectId/$videoId'
      path: '/$videoId'
      fullPath: '/dashboard/$teamSlug/$projectId/$videoId'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdVideoIdRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/$projectId/doc/$contractId': {
      id: '/dashboard/$teamSlug/$projectId/doc/$contractId'
      path: '/doc/$contractId'
      fullPath: '/dashboard/$teamSlug/$projectId/doc/$contractId'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdDocContractIdRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
    '/dashboard/$teamSlug/$projectId/contract_/$contractId': {
      id: '/dashboard/$teamSlug/$projectId/contract_/$contractId'
      path: '/contract/$contractId'
      fullPath: '/dashboard/$teamSlug/$projectId/contract/$contractId'
      preLoaderRoute: typeof DashboardTeamSlugProjectIdContractContractIdRouteImport
      parentRoute: typeof DashboardTeamSlugProjectIdRoute
    }
  }
}

interface DashboardTeamSlugProjectIdRouteChildren {
  DashboardTeamSlugProjectIdVideoIdRoute: typeof DashboardTeamSlugProjectIdVideoIdRoute
  DashboardTeamSlugProjectIdContractRoute: typeof DashboardTeamSlugProjectIdContractRoute
  DashboardTeamSlugProjectIdEditorRoute: typeof DashboardTeamSlugProjectIdEditorRoute
  DashboardTeamSlugProjectIdPlaybackLabRoute: typeof DashboardTeamSlugProjectIdPlaybackLabRoute
  DashboardTeamSlugProjectIdIndexRoute: typeof DashboardTeamSlugProjectIdIndexRoute
  DashboardTeamSlugProjectIdContractContractIdRoute: typeof DashboardTeamSlugProjectIdContractContractIdRoute
  DashboardTeamSlugProjectIdDocContractIdRoute: typeof DashboardTeamSlugProjectIdDocContractIdRoute
}

const DashboardTeamSlugProjectIdRouteChildren: DashboardTeamSlugProjectIdRouteChildren =
  {
    DashboardTeamSlugProjectIdVideoIdRoute:
      DashboardTeamSlugProjectIdVideoIdRoute,
    DashboardTeamSlugProjectIdContractRoute:
      DashboardTeamSlugProjectIdContractRoute,
    DashboardTeamSlugProjectIdEditorRoute:
      DashboardTeamSlugProjectIdEditorRoute,
    DashboardTeamSlugProjectIdPlaybackLabRoute:
      DashboardTeamSlugProjectIdPlaybackLabRoute,
    DashboardTeamSlugProjectIdIndexRoute: DashboardTeamSlugProjectIdIndexRoute,
    DashboardTeamSlugProjectIdContractContractIdRoute:
      DashboardTeamSlugProjectIdContractContractIdRoute,
    DashboardTeamSlugProjectIdDocContractIdRoute:
      DashboardTeamSlugProjectIdDocContractIdRoute,
  }

const DashboardTeamSlugProjectIdRouteWithChildren =
  DashboardTeamSlugProjectIdRoute._addFileChildren(
    DashboardTeamSlugProjectIdRouteChildren,
  )

interface DashboardTeamSlugSettingsRouteChildren {
  DashboardTeamSlugSettingsFoldersRoute: typeof DashboardTeamSlugSettingsFoldersRoute
  DashboardTeamSlugSettingsPayoutsRoute: typeof DashboardTeamSlugSettingsPayoutsRoute
  DashboardTeamSlugSettingsIndexRoute: typeof DashboardTeamSlugSettingsIndexRoute
}

const DashboardTeamSlugSettingsRouteChildren: DashboardTeamSlugSettingsRouteChildren =
  {
    DashboardTeamSlugSettingsFoldersRoute:
      DashboardTeamSlugSettingsFoldersRoute,
    DashboardTeamSlugSettingsPayoutsRoute:
      DashboardTeamSlugSettingsPayoutsRoute,
    DashboardTeamSlugSettingsIndexRoute: DashboardTeamSlugSettingsIndexRoute,
  }

const DashboardTeamSlugSettingsRouteWithChildren =
  DashboardTeamSlugSettingsRoute._addFileChildren(
    DashboardTeamSlugSettingsRouteChildren,
  )

interface DashboardTeamSlugRouteChildren {
  DashboardTeamSlugProjectIdRoute: typeof DashboardTeamSlugProjectIdRouteWithChildren
  DashboardTeamSlugInvoicesRoute: typeof DashboardTeamSlugInvoicesRoute
  DashboardTeamSlugSettingsRoute: typeof DashboardTeamSlugSettingsRouteWithChildren
  DashboardTeamSlugIndexRoute: typeof DashboardTeamSlugIndexRoute
  DashboardTeamSlugInvoicesInvoiceIdRoute: typeof DashboardTeamSlugInvoicesInvoiceIdRoute
}

const DashboardTeamSlugRouteChildren: DashboardTeamSlugRouteChildren = {
  DashboardTeamSlugProjectIdRoute: DashboardTeamSlugProjectIdRouteWithChildren,
  DashboardTeamSlugInvoicesRoute: DashboardTeamSlugInvoicesRoute,
  DashboardTeamSlugSettingsRoute: DashboardTeamSlugSettingsRouteWithChildren,
  DashboardTeamSlugIndexRoute: DashboardTeamSlugIndexRoute,
  DashboardTeamSlugInvoicesInvoiceIdRoute:
    DashboardTeamSlugInvoicesInvoiceIdRoute,
}

const DashboardTeamSlugRouteWithChildren =
  DashboardTeamSlugRoute._addFileChildren(DashboardTeamSlugRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardTeamSlugRoute: typeof DashboardTeamSlugRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardTeamSlugRoute: DashboardTeamSlugRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ConnectDesktopRoute: ConnectDesktopRoute,
  MonoRoute: MonoRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  CTokenRoute: CTokenRoute,
  CompareFrameioRoute: CompareFrameioRoute,
  CompareLucidlinkRoute: CompareLucidlinkRoute,
  CompareWipsterRoute: CompareWipsterRoute,
  ForAgenciesRoute: ForAgenciesRoute,
  ForVideoEditorsRoute: ForVideoEditorsRoute,
  InviteTokenRoute: InviteTokenRoute,
  PayTokenRoute: PayTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  SignTokenRoute: SignTokenRoute,
  WatchPublicIdRoute: WatchPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
